version: '3.8'

services:
  db:
    image: postgres:15  # Use version 15 to avoid incompatibility with version 17
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use this for the volume mount

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: unless-stopped  # Optional: ensures the container restarts unless stopped manually

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped  # Optional: ensures the container restarts unless stopped manually

volumes:
  postgres_data:  # Define the volume here only once
